project_name: arcgis-server-etl
description: ETL project for ArcGIS Server data extraction and processing.
author: Andres Chirinos
created_date: 2025-07-02
version: 1.0.0

output_dir: output
data_dir: data

github_actions:
  artifact:
    logs:
      retention_days: 7
    data:
      retention_days: 14

drive:
  folder_id: "1daaekoNoEUZhffclV3Rv03FmbmHn-JBA"
